### ISSUE TITLE
[question][unrelated]

### ISSUE THREAD

**Issue by rabbitknight** [WassimErriha/NewsFeed#1]
Sorry for unrelated question. with this repo.
I'm coming from [5861](https://github.com/google/ExoPlayer/issues/5861)/
[2600](https://github.com/google/ExoPlayer/issues/2600).
The similar question bother me.Did u has any progress of that?

--- 
I't very import to me!!
TKS!!!

**Comment by WassimErriha** [comment]
I'm still digging into the library. What is your use case. I will try to help if I can.

**Comment by rabbitknight** [comment]
I've  solved the problem!
1. You can do seamless select track by custom TrackSelection(extend BaseTrackSelection)!
2. AND!! DASH may just work fine!.
3. BUT!! When it comes to HLS you should do more work!!
4. MORE!! **CORE CODE** or **KEY WORD**  is `discardUpstream` and `getPreferredQueueSize`

**Comment by rabbitknight** [comment]
The code is not convenient to show you.
The core user case is selecting special track and notify the trackChanged Event.
